application: wwb-index 
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /cv\.pdf
  static_files: static/cv.pdf
  upload: static/cv.pdf
  
- url: /vim\.html
  static_files: static/vim.html
  upload: static/vim.html
  
- url: /static
  static_dir: static
    
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html 

